---
name: Update Technical Docs Link
on:
  workflow_dispatch: {}
  push:
    branches: [docs-v*]
  workflow_call:
    inputs:
      branch:
        type: string
        description: The branch to update the technical docs link.
        required: true
permissions:
  actions: read
  contents: write
  pull-requests: write
  packages: write
  id-token: write
jobs:
  update-docs-link:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: gh-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ steps.gh-app-token.outputs.token }}
      - name: Use branch input
        id: get_branch
        run: |
          if [ -n "${{ inputs.branch }}" ]; then
            echo "Using provided branch input: ${{ inputs.branch }}"
            echo "branch=${{ inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "No branch input provided, deriving from GITHUB_REF"
            branch="${GITHUB_REF#refs/heads/}"
            echo "Derived branch from ref: $branch"
            echo "branch=$branch" >> $GITHUB_OUTPUT
          fi
      - name: Create Pull Request to update the technical docs version
        if: ${{ steps.get_branch.outputs.branch != '' && steps.update-docs.outputs.changed == 'true' }}
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ steps.gh-app-token.outputs.token }}
          title: 'docs: Update technical docs version in the nav.adoc file'
          body: Automatically generated PR to update technical docs version in the nav.adoc file.
          branch-suffix: short-commit-hash
          sign-commits: true
          commit-message: 'docs: Update technical docs version in the nav.adoc file'
